site_name: zio-maelstrom
site_url: https://zio-maelstrom.bilal-fazlani.com
site_description: Learn distributed systems in Scala using ZIO and Maelstrom
repo_name: "bilal-fazlani/zio-maelstrom"
repo_url: "https://github.com/bilal-fazlani/zio-maelstrom"
strict: !ENV [CI, false]

theme:
  name: "material"
  favicon: imgs/logo.svg
  logo: imgs/logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.prune
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips
    - content.code.annotate

markdown_extensions:
  - abbr
  - def_list
  - admonition
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.snippets:
      check_paths: true
      dedent_subsections: true
      base_path:
        - includes
  - pymdownx.highlight:
      linenums: false
      anchor_linenums: false
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      nbsp: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "#"

plugins:
  - search
  - typeset
  - autolinks
  - meta
  - codeinclude:
      title_mode: mkdocs-material
  - social:
      cards_layout: custom
      debug: false
      debug_color: yellow
      cards_layout_dir: social-preview
      concurrency: !ENV [CONCURRENY, 2]
  - awesome-pages:
      collapse_single_pages: true
      strict: !ENV [CI, false]

nav:
  - Home: index.md
  - Documentation: documentation/index.md
  - Examples:
      - examples/echo.md
      - examples/unique-ids.md
      - examples/broadcast.md

#Customization
extra_css:
  - stylesheets/styles.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/bilal-fazlani"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/bilal_fazlani"
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/bilal-fazlani/"

copyright: Copyright &copy 2023 Bilal Fazlani
