name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - 'netlify.toml'
      - '**/release.yml'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - 'netlify.toml'
      - '**/release.yml'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
        name: Cache Coursier
      - uses: coursier/setup-action@v1
        name: Setup Coursier
        with:
          jvm: graalvm-community:21.0.2
          apps: sbt
      - name: Compile and run tests
        run: sbt ";clean ;+test"
