name: Release
on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "mkdocs.yml"
      - "requirements.txt"
      - "netlify.toml"
      - "**/build.yml"
      - "examples/"
      - ".gitignore"
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
        name: Cache Coursier
      - uses: coursier/setup-action@v1
        name: Setup Coursier
        with:
          jvm: graalvm-community:21.0.2
          apps: sbt
      - name: Publish ${{ github.ref }}
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
